# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aea0b9667a1a147cd9e7c7ed249af756516419dfa9ec80c619791ec988966995205bc9442fb7a98bd96a87a769da4985c9b1e5eb4a56624e4aba96ddae7b09e4

test:
  secret_key_base: 2124354ab654fea322aa04c2882c6fafa6e8feafc155afe44d13775991d408dcaf2f493507216c8ec14c8a523d345839d833da795b3dd0cbbd11a57b93eb25b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
